
Public Class frmGenerateSpecialCharges

    Dim ids As String = ""
    Private Sub Button2_Click(sender As Object, e As EventArgs) Handles Button2.Click
        Me.Dispose()

    End Sub

    Private Sub Button3_Click(sender As Object, e As EventArgs) Handles Button3.Click
        If MsgBox("Generate " & cmbCharges.Text & "?", MsgBoxStyle.Question + MsgBoxStyle.YesNo) = MsgBoxResult.Yes Then

            lblPleaseWait.Visible = True
            Dim xlApp As New Microsoft.Office.Interop.Excel.Application
            Dim xlWorkBook As Microsoft.Office.Interop.Excel.Workbook
            Dim xlWorkSheet As Microsoft.Office.Interop.Excel.Worksheet

            Dim Fontweight As Boolean = False
            Dim FontCol As Color = Color.Black

            Dim sRow = 7, Col As Integer = 1

            Dim curRow As Integer = sRow



            'xlApp = New Excel.ApplicationClass
            'xlApp = New Microsoft.Office.Interop.Excel.ApplicationClass
            If cmbCharges.Text = "STORAGE CHARGES" Then
                xlWorkBook = xlApp.Workbooks.Add("\\192.168.10.213\SoftwareApps\CENTRALIZED_SYSTEM\SYSTEM_REPORTS\KYW\STORAGE_CHARGES.xlsx")
            ElseIf cmbCharges.Text = "TRUCKING CHARGES" Then
                xlWorkBook = xlApp.Workbooks.Add("\\192.168.10.213\SoftwareApps\CENTRALIZED_SYSTEM\SYSTEM_REPORTS\KYW\TRUCKING_CHARGES.xlsx")
            End If


            xlWorkSheet = xlWorkBook.Sheets("sheet1")
            'xlApp.Visible = True


            xlWorkSheet.Rows(7).select()
            xlWorkSheet.Rows(5).select()

            InputTextComplete("A3: A3", True, 15.0, 16, 10, "Calibri", "L", "Date RANGE: " & Format(CDate(dtFrom.Value), "MM-dd-yyyy") & " - " & Format(CDate(dtTo.Value), "MM-dd-yyyy"), False, xlWorkSheet, Color.Black, 0)
            InputTextComplete("A4:A4", True, 15.0, 16, 10, "Calibri", "L", "GENERATED BY: " & FNAME & " " & LNAME, False, xlWorkSheet, Color.Black, 0)

            If cmbCharges.Text = "STORAGE CHARGES" Then
                InputTextComplete(ColumnIndexToColumnLetter(8) & 8 & ":" & ColumnIndexToColumnLetter(8) & 8, True, 30, 43.3, 11, "Calibri", "C", "GATE-IN", True, xlWorkSheet, FontCol, 0)
                xlWorkSheet.Range(ColumnIndexToColumnLetter(8) & 8 & ":" & ColumnIndexToColumnLetter(8) & 8).Borders.LineStyle = Microsoft.Office.Interop.Excel.XlLineStyle.xlContinuous


                InputTextComplete(ColumnIndexToColumnLetter(9) & 8 & ":" & ColumnIndexToColumnLetter(9) & 8, True, 30, 43.3, 11, "Calibri", "C", "START BILLABLE" & vbCrLf & "DAY", True, xlWorkSheet, FontCol, 0)
                xlWorkSheet.Range(ColumnIndexToColumnLetter(9) & 8 & ":" & ColumnIndexToColumnLetter(9) & 8).Borders.LineStyle = Microsoft.Office.Interop.Excel.XlLineStyle.xlContinuous


                InputTextComplete(ColumnIndexToColumnLetter(10) & 8 & ":" & ColumnIndexToColumnLetter(10) & 8, True, 30, 43.3, 11, "Calibri", "C", "END BILLABLE" & vbCrLf & "DAY", True, xlWorkSheet, FontCol, 0)
                xlWorkSheet.Range(ColumnIndexToColumnLetter(10) & 8 & ":" & ColumnIndexToColumnLetter(10) & 8).Borders.LineStyle = Microsoft.Office.Interop.Excel.XlLineStyle.xlContinuous


                InputTextComplete(ColumnIndexToColumnLetter(11) & 8 & ":" & ColumnIndexToColumnLetter(11) & 8, True, 30, 43.3, 11, "Calibri", "C", "NO. OF DAYS", True, xlWorkSheet, FontCol, 0)
                xlWorkSheet.Range(ColumnIndexToColumnLetter(11) & 8 & ":" & ColumnIndexToColumnLetter(11) & 8).Borders.LineStyle = Microsoft.Office.Interop.Excel.XlLineStyle.xlContinuous
            ElseIf cmbCharges.Text = "TRUCKING CHARGES" Then
                'InputTextComplete(ColumnIndexToColumnLetter(8) & 8 & ":" & ColumnIndexToColumnLetter(8) & 8, True, 30, 43.3, 11, "Calibri", "C", "TRUCKING" & vbCrLf & " WAIT FEE", True, xlWorkSheet, FontCol, 0)
                'xlWorkSheet.Range(ColumnIndexToColumnLetter(8) & 8 & ":" & ColumnIndexToColumnLetter(8) & 8).Borders.LineStyle = Microsoft.Office.Interop.Excel.XlLineStyle.xlContinuous


                'InputTextComplete(ColumnIndexToColumnLetter(9) & 8 & ":" & ColumnIndexToColumnLetter(9) & 8, True, 30, 43.3, 11, "Calibri", "C", "START BILLABLE" & vbCrLf & "DAY", True, xlWorkSheet, FontCol, 0)
                'xlWorkSheet.Range(ColumnIndexToColumnLetter(9) & 8 & ":" & ColumnIndexToColumnLetter(9) & 8).Borders.LineStyle = Microsoft.Office.Interop.Excel.XlLineStyle.xlContinuous


                'InputTextComplete(ColumnIndexToColumnLetter(10) & 8 & ":" & ColumnIndexToColumnLetter(10) & 8, True, 30, 43.3, 11, "Calibri", "C", "END BILLABLE" & vbCrLf & "DAY", True, xlWorkSheet, FontCol, 0)
                'xlWorkSheet.Range(ColumnIndexToColumnLetter(10) & 8 & ":" & ColumnIndexToColumnLetter(10) & 8).Borders.LineStyle = Microsoft.Office.Interop.Excel.XlLineStyle.xlContinuous


                'InputTextComplete(ColumnIndexToColumnLetter(11) & 8 & ":" & ColumnIndexToColumnLetter(11) & 8, True, 30, 43.3, 11, "Calibri", "C", "NO. OF DAYS", True, xlWorkSheet, FontCol, 0)
                'xlWorkSheet.Range(ColumnIndexToColumnLetter(11) & 8 & ":" & ColumnIndexToColumnLetter(11) & 8).Borders.LineStyle = Microsoft.Office.Interop.Excel.XlLineStyle.xlContinuous

            End If

            Dim icH As Integer = 0
            Dim curHead As Integer = 8



            Dim Dbo As New SQLClass
            Dbo.SqlCon.Open()
            'SQL = "select shippername, shipperAddress, eRate, blno, containerNo, sizeIs, RateIs, feederVesselName, feederVesselVoyage, motherVesselName, motherVesselVoyage from TBL_OTHER_CHARGES where stat = '1' and clock = '0' order by feederVesselName + ' ' + feederVesselVoyage, motherVesselName + ' ' + motherVesselVoyage"
            If cmbCharges.Text = "STORAGE CHARGES" Then
                SQL = "select feederVesselName + ' ' + feederVesselVoyage, motherVesselName + ' ' + motherVesselVoyage from TBL_OTHER_CHARGES where stat = '1' and clock = '0' and convert(date,gateIn) between '" & dtFrom.Value & "' and '" & dtTo.Value & "' AND feederVesselName + ' ' + feederVesselVoyage = '" & KVal(cmbFeederVessel.Text) & " " & cmbVoyage.Text & "'  and blno like '%" & txtBLNo.Text & "%' and ChargesName = '" & KVal(cmbCharges.Text) & "'  group by feederVesselName + ' ' + feederVesselVoyage, motherVesselName + ' ' + motherVesselVoyage order by feederVesselName + ' ' + feederVesselVoyage, motherVesselName + ' ' + motherVesselVoyage"
            ElseIf cmbCharges.Text = "TRUCKING CHARGES" Then
                SQL = "select feederVesselName + ' ' + feederVesselVoyage, motherVesselName + ' ' + motherVesselVoyage from TBL_OTHER_CHARGES where stat = '1' and clock = '0' and convert(date,DATEaDDED) between '" & dtFrom.Value & "' and '" & dtTo.Value & "' AND feederVesselName + ' ' + feederVesselVoyage = '" & KVal(cmbFeederVessel.Text) & " " & cmbVoyage.Text & "'  and blno like '%" & txtBLNo.Text & "%' and ChargesName = '" & KVal(cmbCharges.Text) & "'  group by feederVesselName + ' ' + feederVesselVoyage, motherVesselName + ' ' + motherVesselVoyage order by feederVesselName + ' ' + feederVesselVoyage, motherVesselName + ' ' + motherVesselVoyage"
            End If

            Dbo.SQLCmd = New SqlClient.SqlCommand(SQL, Dbo.SqlCon)
            Dbo.reader = Dbo.SQLCmd.ExecuteReader
            Do While Dbo.reader.Read

                If icH = 1 Then
                    'xlWorkSheet.Rows(8).select()
                    'xlWorkBook.ActiveSheet.copy
                    'xlWorkSheet.Rows(curRow).paste


                    curRow = curRow + 1
                    curHead = curRow

                    Col = 1
                    InputTextComplete(ColumnIndexToColumnLetter(Col) & curRow & ":" & ColumnIndexToColumnLetter(Col + 2) & curRow, True, 15.0, 15.0, 11, "Calibri Italic", "L", "", True, xlWorkSheet, Color.SteelBlue, 0)
                    InputTextComplete(ColumnIndexToColumnLetter(4) & curRow & ":" & ColumnIndexToColumnLetter(7) & curRow, True, 15.0, 15.0, 11, "Calibri Italic", "L", "", True, xlWorkSheet, Color.SteelBlue, 0)
                    curRow = curRow + 1
                    Col = 1
                    InputTextComplete(ColumnIndexToColumnLetter(Col) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow, True, 15.0, 43.3, 11, "Calibri", "C", "SHIPPER", True, xlWorkSheet, FontCol, 0)
                    xlWorkSheet.Range(ColumnIndexToColumnLetter(Col) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow).Borders.LineStyle = Microsoft.Office.Interop.Excel.XlLineStyle.xlContinuous

                    Col = Col + 1
                    InputTextComplete(ColumnIndexToColumnLetter(Col) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow, True, 15.0, 15, 11, "Calibri", "C", "E.R.", True, xlWorkSheet, FontCol, 0)
                    xlWorkSheet.Range(ColumnIndexToColumnLetter(Col) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow).Borders.LineStyle = Microsoft.Office.Interop.Excel.XlLineStyle.xlContinuous

                    Col = Col + 1
                    InputTextComplete(ColumnIndexToColumnLetter(Col) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow, True, 15.0, 15, 11, "Calibri", "C", "B/L NO.", True, xlWorkSheet, FontCol, 0)
                    xlWorkSheet.Range(ColumnIndexToColumnLetter(Col) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow).Borders.LineStyle = Microsoft.Office.Interop.Excel.XlLineStyle.xlContinuous

                    Col = Col + 1
                    InputTextComplete(ColumnIndexToColumnLetter(Col) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow, True, 15.0, 15, 11, "Calibri", "C", "CNTR. NO.", True, xlWorkSheet, FontCol, 0)
                    xlWorkSheet.Range(ColumnIndexToColumnLetter(Col) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow).Borders.LineStyle = Microsoft.Office.Interop.Excel.XlLineStyle.xlContinuous

                    Col = Col + 1
                    InputTextComplete(ColumnIndexToColumnLetter(Col) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow, True, 15.0, 15, 11, "Calibri", "C", "SIZE", True, xlWorkSheet, FontCol, 0)
                    xlWorkSheet.Range(ColumnIndexToColumnLetter(Col) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow).Borders.LineStyle = Microsoft.Office.Interop.Excel.XlLineStyle.xlContinuous

                    Col = Col + 1
                    InputTextComplete(ColumnIndexToColumnLetter(Col) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow, True, 15.0, 15, 11, "Calibri", "C", "CURRENCY", True, xlWorkSheet, FontCol, 0)
                    xlWorkSheet.Range(ColumnIndexToColumnLetter(Col) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow).Borders.LineStyle = Microsoft.Office.Interop.Excel.XlLineStyle.xlContinuous

                    Col = Col + 1
                    InputTextComplete(ColumnIndexToColumnLetter(Col) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow, True, 15.0, 15, 11, "Calibri", "C", "CHARGES", True, xlWorkSheet, FontCol, 0)
                    xlWorkSheet.Range(ColumnIndexToColumnLetter(Col) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow).Borders.LineStyle = Microsoft.Office.Interop.Excel.XlLineStyle.xlContinuous

                    If cmbCharges.Text.ToString.Contains("STORAGE") Then
                        '------------------------------STORAGE ONLY
                        Col = Col + 1
                        InputTextComplete(ColumnIndexToColumnLetter(Col) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow, True, 30, 15, 11, "Calibri", "C", "GATE-IN", True, xlWorkSheet, FontCol, 0)
                        xlWorkSheet.Range(ColumnIndexToColumnLetter(Col) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow).Borders.LineStyle = Microsoft.Office.Interop.Excel.XlLineStyle.xlContinuous

                        Col = Col + 1
                        InputTextComplete(ColumnIndexToColumnLetter(Col) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow, True, 30, 15, 11, "Calibri", "C", "START BILLABLE" & vbLf & "DAY", True, xlWorkSheet, FontCol, 0)
                        xlWorkSheet.Range(ColumnIndexToColumnLetter(Col) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow).Borders.LineStyle = Microsoft.Office.Interop.Excel.XlLineStyle.xlContinuous

                        Col = Col + 1
                        InputTextComplete(ColumnIndexToColumnLetter(Col) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow, True, 30, 15, 11, "Calibri", "C", "END BILLABLE" & vbLf & "DAY", True, xlWorkSheet, FontCol, 0)
                        xlWorkSheet.Range(ColumnIndexToColumnLetter(Col) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow).Borders.LineStyle = Microsoft.Office.Interop.Excel.XlLineStyle.xlContinuous

                        Col = Col + 1
                        InputTextComplete(ColumnIndexToColumnLetter(Col) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow, True, 30, 15, 11, "Calibri", "C", "NO. OF DAYS", True, xlWorkSheet, FontCol, 0)
                        xlWorkSheet.Range(ColumnIndexToColumnLetter(Col) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow).Borders.LineStyle = Microsoft.Office.Interop.Excel.XlLineStyle.xlContinuous
                        '------------------------------
                    ElseIf cmbCharges.Text.ToString.Contains("TRUCKING") Then

                        Col = Col + 1
                        InputTextComplete(ColumnIndexToColumnLetter(Col) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow, True, 30, 15, 11, "Calibri", "C", "CURRENCY", True, xlWorkSheet, FontCol, 0)
                        'xlWorkSheet.Range(ColumnIndexToColumnLetter(Col) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow).Borders.LineStyle = Microsoft.Office.Interop.Excel.XlLineStyle.xlContinuous

                        Col = Col + 1
                        InputTextComplete(ColumnIndexToColumnLetter(Col) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow, True, 30, 15, 11, "Calibri", "C", "TRUCKING" & vbLf & "WAIT FEE", True, xlWorkSheet, FontCol, 0)
                        xlWorkSheet.Range(ColumnIndexToColumnLetter(Col - 1) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow).Borders.LineStyle = Microsoft.Office.Interop.Excel.XlLineStyle.xlContinuous
                        xlWorkSheet.Range(ColumnIndexToColumnLetter(Col - 1) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow).BorderAround(Microsoft.Office.Interop.Excel.XlLineStyle.xlContinuous, Microsoft.Office.Interop.Excel.XlBorderWeight.xlMedium)
                        '------------------------------
                    End If






                    InputTextComplete(ColumnIndexToColumnLetter(1) & curHead & ":" & ColumnIndexToColumnLetter(1) & curHead, True, 15.0, 15, 10, "Calibri Italic", "L", "FEEDER VESSEL: " & Dbo.reader(0).ToString, True, xlWorkSheet, Color.Black, 0)
                    xlWorkSheet.Range(ColumnIndexToColumnLetter(1) & curHead & ":" & ColumnIndexToColumnLetter(3) & curHead).Borders.LineStyle = Microsoft.Office.Interop.Excel.XlLineStyle.xlContinuous

                    InputTextComplete(ColumnIndexToColumnLetter(4) & curHead & ":" & ColumnIndexToColumnLetter(4) & curHead, True, 15.0, 15, 10, "Calibri Italic", "L", "MOTHER VESSEL: " & Dbo.reader(1).ToString, True, xlWorkSheet, Color.Black, 0)
                    xlWorkSheet.Range(ColumnIndexToColumnLetter(4) & curHead & ":" & ColumnIndexToColumnLetter(7) & curHead).Borders.LineStyle = Microsoft.Office.Interop.Excel.XlLineStyle.xlContinuous

                    curRow = curRow + 1




                End If


                If Not icH = 1 Then
                    Col = 1
                    InputTextComplete(ColumnIndexToColumnLetter(Col) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow, True, 15.0, 15, 10, "Calibri Italic", "L", "FEEDER VESSEL: " & Dbo.reader(0).ToString, True, xlWorkSheet, Color.SteelBlue, 0)
                    xlWorkSheet.Range(ColumnIndexToColumnLetter(1) & curRow & ":" & ColumnIndexToColumnLetter(3) & curRow).Borders.LineStyle = Microsoft.Office.Interop.Excel.XlLineStyle.xlContinuous

                    Col = Col + 3
                    InputTextComplete(ColumnIndexToColumnLetter(Col) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow, True, 15.0, 15, 10, "Calibri Italic", "L", "MOTHER VESSEL: " & Dbo.reader(1).ToString, True, xlWorkSheet, Color.SteelBlue, 0)
                    xlWorkSheet.Range(ColumnIndexToColumnLetter(4) & curRow & ":" & ColumnIndexToColumnLetter(7) & curRow).Borders.LineStyle = Microsoft.Office.Interop.Excel.XlLineStyle.xlContinuous

                    Col = 1
                    curRow = curRow + 2
                End If


                Call LoadSub(Col, curRow, Fontweight, xlWorkSheet, FontCol, Dbo.reader(0).ToString, Dbo.reader(1).ToString, txtBLNo.Text)

                'xlWorkSheet.Range(ColumnIndexToColumnLetter(1) & curHead - IIf(icH = 1, 0, 1) & ":" & ColumnIndexToColumnLetter(10) & curRow).Borders.LineStyle = Microsoft.Office.Interop.Excel.XlLineStyle.xlContinuous
                Col = 1
                curRow = curRow + 8
                icH = 1
            Loop
            Dbo.reader.Close()
            Dbo.SqlCon.Close()


            curRow = curRow + 4

            InputTextComplete(ColumnIndexToColumnLetter(1) & curRow & ":" & ColumnIndexToColumnLetter(1) & curRow, True, 15.0, 43.3, 10, "Calibri Italic", "L", "APPROVED BY:", True, xlWorkSheet, Color.Black, 0)

            curRow = curRow + 2
            InputTextComplete(ColumnIndexToColumnLetter(1) & curRow & ":" & ColumnIndexToColumnLetter(1) & curRow, True, 15.0, 43.3, 10, "Calibri Italic", "C", "CHRISTINE FAMINIAL", True, xlWorkSheet, Color.Black, 0)
            xlWorkSheet.Range(ColumnIndexToColumnLetter(1) & curRow & ":" & ColumnIndexToColumnLetter(1) & curRow).Borders(Microsoft.Office.Interop.Excel.XlBordersIndex.xlEdgeTop).LineStyle = Microsoft.Office.Interop.Excel.XlLineStyle.xlContinuous



            MsgBox("Done!", MsgBoxStyle.Information)
            xlWorkSheet.Protect("IT_ADMIN123")
            xlApp.Visible = True
            lblPleaseWait.Visible = False


            If MsgBox("Are you sure you want to submit this record to accounting?", MsgBoxStyle.Question + MsgBoxStyle.YesNo) = MsgBoxResult.Yes Then
                Dim idstr As String()
                idstr = ids.Split("|")
                For i As Integer = 0 To idstr.Length - 1
                    Call SetJob("update TBL_OTHER_CHARGES set clock = '1', submittedBy = '" & USER_ID & "', dateSubmitted = '" & Now & "' where clock = '0' and id = '" & idstr(i) & "'")
                Next
                MsgBox("Done!", MsgBoxStyle.Information)
            End If

        End If
    End Sub

    Public Sub LoadSub(Col As Integer, curRow As Integer, Fontweight As Boolean, xlWorkSheet As Microsoft.Office.Interop.Excel.Worksheet, FontCol As Color, FeederAndVoyage As String, MotherAndVoyage As String, blno As String)
        Dim Dbo As New SQLClass
        Dbo.SqlCon.Open()
        If cmbCharges.Text = "STORAGE CHARGES" Then
            SQL = "select shippername, shipperAddress, eRate, blno, containerNo, sizeIs, RateIs, feederVesselName, feederVesselVoyage, motherVesselName, motherVesselVoyage, Curr, gateIn, startBillDate, endBillDate, nosOfDay, id, truckingWaitFeeCurr, truckingWaitFee from TBL_OTHER_CHARGES where stat = '1' and clock = '0' and convert(date,gateIn) between '" & dtFrom.Value & "' and '" & dtTo.Value & "'  and feederVesselName + ' ' + feederVesselVoyage = '" & FeederAndVoyage & "' and motherVesselName + ' ' + motherVesselVoyage = '" & MotherAndVoyage & "' and blno like '%" & blno & "%' and ChargesName = '" & KVal(cmbCharges.Text) & "' order by feederVesselName + ' ' + feederVesselVoyage, motherVesselName + ' ' + motherVesselVoyage"

        ElseIf cmbCharges.Text = "TRUCKING CHARGES" Then
            SQL = "select shippername, shipperAddress, eRate, blno, containerNo, sizeIs, RateIs, feederVesselName, feederVesselVoyage, motherVesselName, motherVesselVoyage, Curr, gateIn, startBillDate, endBillDate, nosOfDay, id, truckingWaitFeeCurr, truckingWaitFee from TBL_OTHER_CHARGES where stat = '1' and clock = '0' and convert(date,dateAdded) between '" & dtFrom.Value & "' and '" & dtTo.Value & "'  and feederVesselName + ' ' + feederVesselVoyage = '" & FeederAndVoyage & "' and motherVesselName + ' ' + motherVesselVoyage = '" & MotherAndVoyage & "' and blno like '%" & blno & "%' and ChargesName = '" & KVal(cmbCharges.Text) & "' order by feederVesselName + ' ' + feederVesselVoyage, motherVesselName + ' ' + motherVesselVoyage"

        End If


        Dbo.SQLCmd = New SqlClient.SqlCommand(SQL, Dbo.SqlCon)
        Dbo.reader = Dbo.SQLCmd.ExecuteReader
        Do While Dbo.reader.Read
            Col = 1
            InputTextComplete(ColumnIndexToColumnLetter(Col) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow, True, 56.25, 43.3, 10, "Calibri Italic", "L", Dbo.reader(0).ToString & vbLf & Dbo.reader(1).ToString, Fontweight, xlWorkSheet, FontCol, 0)
            xlWorkSheet.Range(ColumnIndexToColumnLetter(Col) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow).Borders.LineStyle = Microsoft.Office.Interop.Excel.XlLineStyle.xlContinuous
            Col = Col + 1
            InputTextComplete(ColumnIndexToColumnLetter(Col) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow, True, 56.25, 15.0, 10, "Calibri Italic", "C", FormatMoney(Dbo.reader(2).ToString), Fontweight, xlWorkSheet, FontCol, 0)
            xlWorkSheet.Range(ColumnIndexToColumnLetter(Col) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow).Borders.LineStyle = Microsoft.Office.Interop.Excel.XlLineStyle.xlContinuous
            Col = Col + 1
            InputTextComplete(ColumnIndexToColumnLetter(Col) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow, True, 56.25, 15.0, 10, "Calibri Italic", "C", Dbo.reader(3).ToString, Fontweight, xlWorkSheet, FontCol, 0)
            xlWorkSheet.Range(ColumnIndexToColumnLetter(Col) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow).Borders.LineStyle = Microsoft.Office.Interop.Excel.XlLineStyle.xlContinuous
            Col = Col + 1
            InputTextComplete(ColumnIndexToColumnLetter(Col) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow, True, 56.25, 15.0, 10, "Calibri Italic", "C", Dbo.reader(4).ToString, Fontweight, xlWorkSheet, FontCol, 0)
            xlWorkSheet.Range(ColumnIndexToColumnLetter(Col) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow).Borders.LineStyle = Microsoft.Office.Interop.Excel.XlLineStyle.xlContinuous

            Col = Col + 1
            InputTextComplete(ColumnIndexToColumnLetter(Col) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow, True, 56.25, 15.0, 10, "Calibri Italic", "C", Dbo.reader(5).ToString, Fontweight, xlWorkSheet, FontCol, 0)
            xlWorkSheet.Range(ColumnIndexToColumnLetter(Col) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow).Borders.LineStyle = Microsoft.Office.Interop.Excel.XlLineStyle.xlContinuous

            Col = Col + 1
            InputTextComplete(ColumnIndexToColumnLetter(Col) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow, True, 56.25, 15.0, 10, "Calibri Italic", "C", Dbo.reader(11).ToString, Fontweight, xlWorkSheet, FontCol, 0)
            xlWorkSheet.Range(ColumnIndexToColumnLetter(Col) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow).Borders.LineStyle = Microsoft.Office.Interop.Excel.XlLineStyle.xlContinuous

            Col = Col + 1
            InputTextComplete(ColumnIndexToColumnLetter(Col) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow, True, 56.25, 15.0, 10, "Calibri Italic", "C", FormatMoney(Dbo.reader(6).ToString), Fontweight, xlWorkSheet, FontCol, 0)
            xlWorkSheet.Range(ColumnIndexToColumnLetter(Col) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow).Borders.LineStyle = Microsoft.Office.Interop.Excel.XlLineStyle.xlContinuous


            If cmbCharges.Text.ToString.Contains("STORAGE") Then
                Col = Col + 1
                InputTextComplete(ColumnIndexToColumnLetter(Col) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow, True, 56.25, 15.0, 10, "Calibri Italic", "C", ShowDateAsKyowa(Dbo.reader(12).ToString), Fontweight, xlWorkSheet, FontCol, 0)
                xlWorkSheet.Range(ColumnIndexToColumnLetter(Col) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow).Borders.LineStyle = Microsoft.Office.Interop.Excel.XlLineStyle.xlContinuous

                Col = Col + 1
                InputTextComplete(ColumnIndexToColumnLetter(Col) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow, True, 56.25, 15.0, 10, "Calibri Italic", "C", ShowDateAsKyowa(Dbo.reader(13).ToString), Fontweight, xlWorkSheet, FontCol, 0)
                xlWorkSheet.Range(ColumnIndexToColumnLetter(Col) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow).Borders.LineStyle = Microsoft.Office.Interop.Excel.XlLineStyle.xlContinuous

                Col = Col + 1
                InputTextComplete(ColumnIndexToColumnLetter(Col) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow, True, 56.25, 15.0, 10, "Calibri Italic", "C", ShowDateAsKyowa(Dbo.reader(14).ToString), Fontweight, xlWorkSheet, FontCol, 0)
                xlWorkSheet.Range(ColumnIndexToColumnLetter(Col) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow).Borders.LineStyle = Microsoft.Office.Interop.Excel.XlLineStyle.xlContinuous

                Col = Col + 1
                InputTextComplete(ColumnIndexToColumnLetter(Col) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow, True, 56.25, 15.0, 10, "Calibri Italic", "C", Dbo.reader(15).ToString, Fontweight, xlWorkSheet, FontCol, 0)
                xlWorkSheet.Range(ColumnIndexToColumnLetter(Col) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow).Borders.LineStyle = Microsoft.Office.Interop.Excel.XlLineStyle.xlContinuous

            ElseIf cmbCharges.Text.ToString.Contains("TRUCKING") Then

                Col = 8
                InputTextComplete(ColumnIndexToColumnLetter(Col) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow, True, 56.25, 15.0, 10, "Calibri Italic", "C", Dbo.reader(17).ToString, Fontweight, xlWorkSheet, FontCol, 0)
                xlWorkSheet.Range(ColumnIndexToColumnLetter(Col) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow).Borders.LineStyle = Microsoft.Office.Interop.Excel.XlLineStyle.xlContinuous

                Col = 9
                InputTextComplete(ColumnIndexToColumnLetter(Col) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow, True, 56.25, 15.0, 10, "Calibri Italic", "C", FormatMoney(Dbo.reader(18).ToString), Fontweight, xlWorkSheet, FontCol, 0)
                xlWorkSheet.Range(ColumnIndexToColumnLetter(Col) & curRow & ":" & ColumnIndexToColumnLetter(Col) & curRow).Borders.LineStyle = Microsoft.Office.Interop.Excel.XlLineStyle.xlContinuous


            End If

            ids = ids & "|" & Dbo.reader(16).ToString

            curRow = curRow + 1
        Loop
        Dbo.reader.Close()
        Dbo.SqlCon.Close()
    End Sub

    Private Sub frmGenerateSpecialCharges_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        With cmbCharges.Items
            .Clear()
            .Add("STORAGE CHARGES")
            .Add("TRUCKING CHARGES")
        End With

        Call LoadStrCmb(cmbFeederVessel, "SELECT ID, VESSELNAME FROM TBL_VESSEL WHERE STAT = '1'")

    End Sub
End Class